### ISSUE TITLE
adm cmds failing

### ISSUE THREAD

**Issue by theycallmereborn** [ineedblood/entmod#1]
amkick, ammerc, amnpc, amkillvote, amlisttele, amlockteam, amlogout, amluaexec, amluareload, ammap, ampoll, amprotect, ampsay,

**Comment by azurda** [comment]
probably overwritting bit values gotta look at it

**Comment by azurda** [comment]
fixed. :> https://github.com/ineedblood/entmod/commit/b69913a7717f9d7664591d10fa890c5286087768
